export const links = [
    {
        title:"Home",
        path:"/"
    },
    {
        title:"About",
        path:"/#about"
    },
    {
        title:"Products",
        path:"/#products"
    },
    {
        title:"Projects",
        path:"/#projects"
    },
    {
        title:"Contact",
        path:"/#contact"
    }
]